### PR TITLE
Hello microverse project pull request

### PR DESCRIPTION
**Pull request by spydaspider**

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @spydaspider , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No linter error 
✔️ Nice implementing the requirements

## Required Changes ♻️

- [x] it would be better if you add a descriptive short summary that tells in more detail what you've done in this Pull Request 
image

- [x] please try to add the name of the project and a little description about the project to the `README` file so in order you project will be professional and well documented 

- [x] Also next time try to capitalize you commits messages in order to follow the [professional rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by spydaspider** [comment]
Thank you very much. I will rectify my errors.

**Comment by spydaspider** [comment]
**Hello Micro verse Project**
Added index.html file.
Added style.css file.
Added HTML code to display the h1 message-Hello Micro verse
Added CSS code to change the color of the h1 element.

**Review by youmari — APPROVED** [review]
# Project Approved :trophy: :tada: 🟢 

Hi @spydaspider 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by youmari** [comment]
> **Hello Micro verse Project** Added index.html file. Added style.css file. Added HTML code to display the h1 message-Hello Micro verse Added CSS code to change the color of the h1 element.

@spydaspider  you should add this as short summary above not as a comment please try to do that

**Comment by spydaspider** [comment]
Awesome, thank you so much!

**Pull request merged**
